# Indexing and Slicing

In [1]:
import numpy as np

In [4]:
a = np.arange(1,8)
a

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
a[0]

np.int64(1)

In [6]:
print(a[-1])

7


In [7]:
print(a[1:5])

[2 3 4 5]


In [8]:
print(a[3:])

[4 5 6 7]


In [9]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
b[2][1]

np.int64(8)

In [12]:
print(b[0][0:2])

[1 2]


In [13]:
# filteration
c= b
c[(c>2) & (c<7)]

array([3, 4, 5, 6])