# Numpy Introduction

In [1]:
# # install the library numpy
# !pip install numpy

In [2]:
# importing the numpy
import numpy as np

In [4]:
# creating a numpy array
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [11]:
# converting one dimensional array to two dimensional array
a2 = a[np.newaxis,:]
a2

array([[0, 1, 2, 3, 4, 5]])

In [6]:
# shape of the array
a2.shape

(1, 6)

In [13]:
c = np.empty((2,3))
c

array([[0.0e+000, 4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323, 2.5e-323]])

In [14]:
# 3D array
d = np.array([[[1, 2, 3], [4, 5, 6]]
              , [[1, 2, 3], [4, 5, 6]]])
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [15]:
d.ndim

3

In [20]:
# array of shape (3,1,4)
a1 = np.array([[[0,1,2,3]],   
              [[4,5,6,7]],  
              [[8,9,10,11]]])
a.shape

(3, 1, 4)

In [22]:
# reshaping the array
a2 = a1.reshape(6,2)
a2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [24]:
# reshaping the array to original
a3 = a2.reshape(3,1,4)
a3

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])