# Matrices

In [3]:
import numpy as np

In [4]:
a = np.arange(0,100,2).reshape(5,10)
a

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [5]:
# a[row:row , column:column]
a[0:5, 0:5]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [6]:
a.min()

np.int64(0)

In [7]:
a.max()

np.int64(98)

In [8]:
a.sum()

np.int64(2450)

In [10]:
a.max(axis=1)

array([18, 38, 58, 78, 98])